web/MGWeb/App/urls.py
from .views import *
from django.urls import path

app_name = 'App'

urlpatterns = [

    path("",home,name='home'),
    path("Prostredi",env,name='env'),
    path("Metody/Matematicka",gmMat,name="gmMat"),
    path("Metody/Kolac",gmPie,name="gmPie"),
    path("Metody/Sloupcovy",gmBar,name="gmBar"),
    path("Metody/Nahodny-sum",gmNo,name="gmNo"),
    path("Konzole",cons,name="cons"),
    path("Stazeni",down,name="down"),
    path("Diskuze-red",disc,name="disk"),
    path("O-autorovi",boutMe,name="boutMe")

]

web/MGWeb/Discussion/urls.py
from .views import *
from django.urls import path

app_name = 'Discussion'

urlpatterns = [

  path("",home, name="home"),
  path("Tvorba",create,name="create"),
  path('<str:slug>',detail,name="detail")

]

web/MGWeb/MGWeb/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("App.urls")),
    path("Diskuze/", include("Discussion.urls")),
    path('accounts/', include('allauth.urls')),
]

web/MGWeb/Discussion/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
# Create your models here.
class Post(models.Model):
    author = models.CharField(max_length=100, default="")
    title = models.CharField(max_length=100,default="")
    text = models.TextField(max_length=1000)
    date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, db_index=True,default="")



    def __str__(self):
        return f"{self.author}, {self.title}...{self.date} "

    def snippet(self):
        return f"{self.text[:50]}..."

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post,related_name="comment",on_delete=models.CASCADE)
    author = models.CharField(max_length=100,default="")
    text = models.TextField(max_length=1000)
    date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.author

web/MGWeb/Discussion/forms.py
from django import forms
from .models import Post,Comment
class MakePost(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["author","title","text"]
    def clean(self):
        if self.is_valid():
            title = self.cleaned_data["title"]
            if Post.objects.filter(title=title).exists():
                raise forms.ValidationError("Title already exists")


class MakeComment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["author","text"]

web/MGWeb/App/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse


# Create your views here.
def home(request):
    return render(request, "home.html")


def env(request):
    return render(request, "env.html")


def gmMat(request):
    return render(request, "gm-mat.html")


def gmPie(request):
    return render(request, "gm-Pie.html")


def gmBar(request):
    return render(request, "gm-bar.html")


def gmNo(request):
    return render(request, "gm-no.html")


def cons(request):
    return render(request, "cons.html")

def down(request):
    return render(request,"down.html")

def disc(request):
    return redirect("Diskuze/")

def boutMe(request):
    return render(request,"boutme.html")

web/MGWeb/Discussion/views.py
from django.shortcuts import render,redirect
from .models import Post,Comment
from .forms import MakePost,MakeComment
# Create your views here.
def home(request):
    posts = Post.objects.all().order_by('-date')
    return render(request,"disc/disc.html",{"posts":posts})

def create(request):
    if request.method == "POST":
        form = MakePost(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Discussion:home")


    else:
        form = MakePost()
    return render(request,"disc/create.html",{"form":form})

def detail(request,slug):
    post = Post.objects.get(slug=slug)
    if request.method == "POST":
        form = MakeComment(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()

            return redirect("Discussion:detail",slug=slug)

    else:
        form = MakeComment()
        comments = Comment.objects.filter(post=post).order_by('-date')

    return render(request,"disc/post.html",{"post":post,"comments":comments,"form":form})

web/MGWeb/templates/base.html
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MarkoGebra</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'App:home' %}"><i class="material-icons">help_outline</i></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link {% block ac1 %}{% endblock %}" href="{% url 'App:env' %}">Prostředí<span class="sr-only">(current)</span></a>
            <li class="nav-item dropdown {% block ac2 %}{% endblock %}">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Grafovací metody
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item {% block ac3 %}{% endblock %}" href="{% url 'App:gmMat' %}">Matematické</a>
                  <a class="dropdown-item {% block ac4 %}{% endblock %}" href="{% url 'App:gmPie' %}">Koláč</a>
                  <a class="dropdown-item {% block ac5 %}{% endblock %}" href="{% url 'App:gmBar' %}">Sloupcový</a>
                  <a class="dropdown-item {% block ac6 %}{% endblock %}" href="{% url 'App:gmNo' %}">Náhodný šum</a>
                </div>
            </li>
            <a class="nav-item nav-link {% block ac7 %}{% endblock %}" href="{% url 'App:cons' %}">Konzole<span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link {% block ac8 %}{% endblock %}" href="{% url 'App:down' %}">Stažení<span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link {% block ac10 %}{% endblock %}" href="{% url 'App:disk' %}">Diskuze<span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link {% block ac9 %}{% endblock %}" href="{% url 'App:boutMe' %}">O autorovi<span class="sr-only">(current)</span></a>

          </div>
        </div>
      </nav>
    {% block content %}

    {% endblock %}
        <footer  class="bg-dark" >
    <div class="">
        <p>© 2020 <a href="#">Marek Procházka</a> - Všechna práva vyhrazena</p>
    </div>
</footer>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

web/MGWeb/templates/boutme.html
{% extends 'base.html' %}
{% load static %}
{% block ac9 %}active{% endblock %}

{% block content %}
<p>Here will be links to my social media, mail and portfolio site</p>
{% endblock %}

web/MGWeb/templates/cons.html
{% extends 'base.html' %}
{% load static %}
{% block ac7 %}active{% endblock %}

{% block content %}
<div class="container-xl mt-5 ml-5 mr-5 ">
    <h3>Konzole</h3>
    <p>Konzole slouží k následné úpravě vzhledu uživatelských vstupů.</p>
    <h5 class="mt-5">Příkazy</h5>
    <ul class="mt-5">
        <li class="mt-3"><a href="#delete">Odstranění</a></li>
        <li class="mt-3"><a href="#markers">Změna značky</a></li>
        <li class="mt-3"><a href="#color">Změna barvy</a></li>
        <li class="mt-3"><a href="#size">Změna velikosti</a></li>
        <li class="mt-3"><a href="#gpstyle">Styl grafu</a></li>
        <li class="mt-3"><a href="#pie">Speciální příkazy koláčového grafování</a></li>
        <li class="mt-3"><a href="#other">Ostatní příkazy konzole</a></li>
    </ul>
</div>
<div class="container-xl mt-5 ml-5 mr-5" id="delete" >
    <h4 class="mt-4">Odstranění</h4>
    <h5>Příkaz: <i>del {index}</i></h5>
    <h5>Použitelné v metodách: všechny</h5>
    <p>Odstraní konkrétní vstup</p>
    <p>Index = pořadové číslo v seznamu vstupů</p>

</div>
<div class="container-xl mt-5 ml-5 mr-5" id="markers" >
    <h4>Změna značky</h4>
    <h5>Příkaz: <i>del {index} {značka}</i></h5>
    <h5>Použitelné v metodách: Matematická, Náhodný šum</h5>
    <p>Mění značku daného vstupu</p>
    <p>Index = pořadové číslo v seznamu vstupů</p>
    <p>Příkaz pro vypsání značek v konzoli: <i>markers</i></p>
    <h5>Značky pro bodový vstup, náhodný šum:</h5>
    <ul class="ml-3">
        <li class="mt-2"><i>ponz.: Některé značky při větší velikosti ztrácí svůj tvar</i></li>
        <li class="mt-2">. = Malý kruh</li>
        <li class="mt-2">, = Čtverec</li>
        <li class="mt-2">o = Velký kruh</li>
        <li class="mt-2">v = Trojúhelník (špička směřuje dolů)</li>
        <li class="mt-2">^ = Trojúhelník (špička směřuje nahoru)</li>
        <li class="mt-2">< = Trojúhelník (špička směřuje doleva)</li>
        <li class="mt-2">> = Trojúhelník (špička směřuje doprava)</li>
        <li class="mt-2">1 = Tvar podobný písmenu Y</li>
        <li class="mt-2">2 = Tvar podobný písmenu Y (orientovaný dolů)</li>
        <li class="mt-2">3 = Tvar podobný písmenu Y (orientovaný doprava)</li>
        <li class="mt-2">4 = Tvar podobný písmenu Y (orientovaný doleva)</li>
        <li class="mt-2">8 = Osmistěn (velmi podobný kruhu)</li>
        <li class="mt-2">s = Čtverec (se zakulacenými rohy)</li>
        <li class="mt-2">p = Pentagon</li>
        <li class="mt-2">P = Tučné plus</li>
        <li class="mt-2">* = Hvězda</li>
        <li class="mt-2">h = Hexagon</li>
        <li class="mt-2">H = Hexagon (ležící)</li>
        <li class="mt-2">+ = Plus</li>
        <li class="mt-2">x = Písmeno x</li>
        <li class="mt-2">X = Písmeno x (tučné)</li>
        <li class="mt-2">D = Diamant (rovnostranný)</li>
        <li class="mt-2">d = Diamant (úzký)</li>
        <li class="mt-2">| = Svislá čára</li>
        <li class="mt-2">_ = Vodorovná čára</li>
    </ul>
    <h5>Značky pro vstup z funkce:</h5>
    <ul class="ml-3">
        <li class="mt-2">- NEBO solid = Plná čára</li>
        <li class="mt-2">-- NEBO dashed = Přerušovaná čára</li>
        <li class="mt-2">-. NEBO dashdot = Čerchovaná čára</li>
        <li class="mt-2">: NEBO dotted = Tečkovaná čára</li>
        <li class="mt-2">(None = Bez značky)</li>
    </ul>
</div>
<div class="container-xl mt-5 ml-5 mr-5" id="color" >
    <h4>Změna barvy</h4>
    <h5>Příkaz: <i>col {index}</i></h5>
    <h5>Použitelné v metodách: všechny</h5>
    <p>Mění barvu daného vstupu</p>
    <p>Index = pořadové číslo v seznamu vstupů</p>
    <p>Po odelsání příkazu se otevře nové okno s volbou barvy</p>

</div>
<div class="container-xl mt-5 ml-5 mr-5" id="size" >
    <h4>Změna velikosti</h4>
    <h5>Příkaz: <i>size {index} {velikost}</i></h5>
    <h5>Použitelné v metodách: Matematická, Sloupcová, Náhodný šum</h5>
    <p>Mění velikost (tlušťku čar/šířku) daného vstupu</p>
    <p>Index = pořadové číslo v seznamu vstupů</p>
    <p>Velikost = celé číslo/desetinné číslo</p>
</div>
<div class="container-xl mt-5 ml-5 mr-5" id="gpstyle" >
 <h4>Změna stylu grafu</h4>
    <h5>Příkaz: <i>GPstyle {style}</i></h5>
    <h5>Použitelné v metodách: Matematická</h5>
    <p>Mění pozadí grafu</p>
    <p>Příkaz pro vypsání stylů v konzoli: <i>ShowMeStyles</i></p>
    <p>Změna se projeví po restartu aplikace</p>
    <p>Dostupné styly:</p>
    <ul class="ml-3">
        <li class="mt-2">Solarize_Light2 = Nažloutlý základní graf (ggplot)</li>
        <li class="mt-2">seaborn-bright = graf bez mřížky</li>
        <li class="mt-2">classic = bez mřížky, šedé okolí</li>
        <li class="mt-2">dark_background = černé pozadí, bez mřížky </li>
        <li class="mt-2">fivethirtyeight = roztažený základní (bez okrajů)</li>
        <li class="mt-2">ggplot = základní graf</li>
        <li class="mt-2">seaborn = modernější font, světle modré pozadí grafu</li>
        <li class="mt-2">seaborn-whitegrid = seaborn, bílé pozadí</li>
        <li class="mt-2">seaborn-dark = seaborn bez mřížky</li>
        <li class="mt-2">seaborn-poster = seaborn bez mřížky, bílé pozadí, popisy os velmým písmem</li>

    </ul>

</div>
<div class="container-xl mt-5 ml-5 mr-5" id="pie" >
 <h4>Speciální příkazy koláčového grafování</h4>
    <h5>Příkaz: <i>explode {index} {value}</i></h5>
    <h5>Použitelné v metodách: Koláč</h5>
    <p>Vysune hodnotu z grafu</p>
    <p>Index = pořadové číslo v seznamu vstupů</p>
    <p>Value = celé číslo/desetinné číslo</p>

    <h5>Příkaz: <i>stAngle {angle}</i></h5>
    <h5>Použitelné v metodách: Koláč</h5>
    <p>Otočí graf (změní jeho počáteční úhel)</p>
    <p>Angle = celé číslo/desetinné číslo (úhel -> 0-360)</p>

</div>
<div class="container-xl mt-5 ml-5 mr-5" id="other" >
    <h4>Ostatní příkazy konzole</h4>
    <h5>Příkaz: <i>clear</i></h5>
    <h5>Vyčištění konzole</h5>
</div>



<div class="last"></div>
{% endblock %}

web/MGWeb/templates/disc/create.html
{% extends 'base.html' %}
{% load static %}
{% block ac10 %}active{% endblock %}

{% block content %}
<div class="container-xl mt-5 ml-5">
    <a class="btn btn-primary" href="{% url 'Discussion:home' %}" role="button">Zpět na přispěvky</a>

    <form action="{% url 'Discussion:create' %}" class="site-form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Zveřejnit" class="btn btn-primary">
    </form>

</div>
{% endblock %}

web/MGWeb/templates/disc/disc.html
{% extends 'base.html' %}
{% load static %}
{% block ac10 %}active{% endblock %}

{% block content %}
<div class="container-xl mt-5 ml-5">

    <a class="btn btn-primary" href="{% url 'Discussion:create' %}" role="button">Vytvořit příspěvek</a>
    <div class="d-flex p-2 bd-highlight">
    {% for post in posts %}
        <div class="card mr-5" style="width: 18rem;">
          <div class="card-body d-flex flex-column">
            <h5 class="card-title">{{post.title}}</h5>
            <p class="card-text">{{post.snippet}}</p>
            <p class="card-text text-right align-self-end mt-auto"><strong> {{post.author}}</strong></p>
            <p class="card-text text-right small align-self-end ">{{post.date}}</p>
            <a href="{% url 'Discussion:detail' slug=post.slug %}" class="btn btn-primary stretched-link  align-self-end">Celý příspěvek</a>
          </div>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

web/MGWeb/templates/disc/post.html
{% extends 'base.html' %}
{% load static %}
{% block ac10 %}active{% endblock %}

{% block content %}
<div class="container-lg mt-5 ml-5">
    <a class="btn btn-primary" href="{% url 'Discussion:home' %}" role="button">Zpět na přispěvky</a>
    <h3>{{post.title}}</h3>
    <p>{{post.text|linebreaks}}</p>
    <p>{{post.author}}</p>
    <p>{{post.date}}</p>

    <div class="comments">
        <h5>Komentáře</h5>
        <form action="{% url 'Discussion:detail' slug=post.slug %}" class="comment-form" method="post">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Zveřejnit komentář" class="btn btn-primary">

        </form>
        {% for comment in comments %}
            <div class="comm pl-2 ">
                <p class="pt-1">{{comment.text|linebreaks}}</p>
                <p class="text-right pr-2"><strong> {{comment.author}}</strong></p>
                <p class="small text-right pr-2 pb-2">{{comment.date}}</p>
            </div>
        {% endfor %}
    </div>
</div>
<div class="last"></div>



{% endblock %}

web/MGWeb/templates/down.html
{% extends 'base.html' %}
{% load static %}
{% block ac8 %}active{% endblock %}

{% block content %}
<p>download link and help</p>
{% endblock %}

web/MGWeb/templates/env.html
{% extends 'base.html' %}
{% load static %}
{% block ac1 %}active{% endblock %}

{% block content %}
<div class="container-lg mt-5 ml-5"><img src="{% static 'imgs/main.png' %}" alt="main1" class="responsive_img_big" ></div>
<div class="container-lg mt-5 ml-5">
    <p id="h-methods" class="h-all" >Přepínač metod grafování</p>
    <p id="h-input" class="h-all">Prostor pro uživatelský vstup</p>
    <p id="h-settings" class="h-all">Nastavení mřížky a další možnosti</p>
    <p id="h-graph" class="h-all">Prostor grafu</p>
    <p id="h-console" class="h-all">Otevření konzole</p>
</div>
<div class="container-lg mt-5 ml-5"><img src="{% static 'imgs/save_as.png' %}" alt="main1" class="responsive_img_small" ></div>
<div class="container-lg mt-5 ml-5">
    <p id="h-name" class="h-all">Název souboru</p>
    <p id="h-place" class="h-all">Volba místa v PC, kam se má graf uložit</p>
    <p id="h-grid" class="h-all">Při zaškrtnutí se graf uloží bez mřížky a popisných os</p>
    <p id="h-save" class="h-all">Uložit</p>
    <p id="h-cancel" class="h-all">Zrušit</p>
</div>
{% endblock %}

web/MGWeb/templates/gm-Pie.html
{% extends 'base.html' %}
{% load static %}
{% block ac2 %}active{% endblock %}
{% block ac4 %}active{% endblock %}

{% block content %}
<div class="container-xl mt-5 ml-5 mr-5 ">
    <h3>Grafování do koláčového grafu</h3>
    <h4 class="mt-5">Vstupy</h4>
    <ul class="ml-3">
        <li>
            <p>Množství</p>
        </li>
        <li>
            <p>Název</p>
        </li>
        <li>
            <p>Barva</p>
        </li>
    </ul>
    <h4 class="mt-5">Množství</h4>
    <p>Určuje množství "jednotek"/protoru, který konktrétní hodnota obsadí v grafu</p>
    <p>Obsazený prostor se poté odvíjí od poměru množství ostatních hodnot </p>
    <h4>Název</h4>
    <p>Určuje jméno hodnoty</p>
    <h4>Barva</h4>
    <p>Výběr barvy - volba ze základních barev</p>
    <p class="last">Posléze lze barvu upravit na libovolnou za pomocí konzole</p>


</div>
{% endblock %}

web/MGWeb/templates/gm-bar.html
{% extends 'base.html' %}
{% load static %}
{% block ac2 %}active{% endblock %}
{% block ac5 %}active{% endblock %}

{% block content %}
<div class="container-xl mt-5 ml-5 mr-5 ">
    <h3>Grafování do sloupcového grafu</h3>
    <p><i>pozn.: Principiálně stejný postup jako u koláčového grafu</i></p>
    <h4 class="mt-5">Vstupy</h4>
    <ul class="ml-3">
        <li>
            <p>Množství</p>
        </li>
        <li>
            <p>Název</p>
        </li>
        <li>
            <p>Barva</p>
        </li>
    </ul>
    <h4 class="mt-5">Množství</h4>
    <p>Určuje množství "jednotek"/protoru, který konktrétní hodnota obsadí v grafu</p>
    <p>Obsazený prostor se poté odvíjí od poměru množství ostatních hodnot </p>
    <h4>Název</h4>
    <p>Určuje jméno hodnoty</p>
    <h4>Barva</h4>
    <p>Výběr barvy - volba ze základních barev</p>
    <p class="last">Posléze lze barvu upravit na libovolnou za pomocí konzole</p>


</div>
{% endblock %}

web/MGWeb/templates/gm-mat.html
{% extends 'base.html' %}
{% load static %}
{% block ac2 %}active{% endblock %}
{% block ac3 %}active{% endblock %}

{% block content %}
<div class="container-xl mt-5 ml-5 mr-5 ">
    <h3>Matematické grafování</h3>
    <h4 class="mt-5 ">Druhy vstupů</h4>
    <p>Matematiacké grafování má v současné době 2 možnosti  vstupu a to <strong>Bodový</strong> a <strong>Funkcionální</strong> vstup.</p>
    <h4 class="mt-5">Bodový vstup</h4>
    <p>Jednoduché zadání souřadnic <strong>X</strong> a <strong>Y</strong>.</p>
    <p>Výsledný bod se po vložení vykreslí na grafu, zapíše se do tabulky pod vstupy a obdrží index (Přidělené číslo v tabulce).</p>
    <p>Bod lze posléze upravit za pomocí konzole, kde je přístupný za pomocí indexu.</p>
    <h4 class="mt-5">Funkcionální vstup</h4>
    <p>Zadává se vždy jen pravá strana funkce.</p>
    <p>Pro příklad u funkce f(x) = (x**2)/2 bude na vstupu uvedena pouze pravá strana.</p>
    <p>Aplikace bere na vstup specificky psané operátory často podobné jako pro jazyk python:</p>
    <ul class="ml-3 ">
        <li>
            <p>* = krát</p>
        </li>
        <li>
            <p>/ = děleno</p>
        </li>
        <li>
            <p>+/- zachováno</p>
        </li>
        <li>
            <p>s = sinus</p>
        </li>
        <li>
            <p>c = cosinus</p>
        </li>
        <li>
            <p>t = tangens</p>
        </li>
        <li>
            <p>p - Pí</p>
        </li>
        <li>
            <p>() = Jediné podporované závorky</p>
        </li>
    </ul>
    <p >Ostatní operátory program zatím nepodporuje</p>
    <p class="last">V případě zlomku je třeba vždy vložit čitatel a jmenovatel do vlastní závorky: <i>(x-2)/(x*7)</i> </p>



</div>
{% endblock %}

web/MGWeb/templates/gm-no.html
{% extends 'base.html' %}
{% load static %}
{% block ac2 %}active{% endblock %}
{% block ac6 %}active{% endblock %}

{% block content %}
<div class="container-xl mt-5 ml-5 mr-5 ">
    <h3>Náhodný šum</h3>
    <h4 class="mt-5">Vstupy</h4>
    <ul class="ml-3">
        <li>
            <p>Množství</p>
        </li>
        <li>
            <p>Rozptyl</p>
        </li>
        <li>
            <p>Barva</p>
        </li>
    </ul>
    <h4>Množství</h4>
    <p>Množství bodů v rozptylu 0-100</p>
    <p>Při změně počtu se náhodně vygeneruje jiný šum</p>
    <h4>rozptyl</h4>
    <p>Rozptyl jednotlivých bodů od sebe</p>
    <h4>Barva</h4>
    <p>Výběr barvy - volba ze základních barev</p>
    <p class>Posléze lze barvu upravit na libovolnou za pomocí konzole</p>
    <h4>Uzamknout</h4>
    <p>Narodíl od předchozích metod, náhodný šum se zobrazuje živě na grafu, pro uložení a tvorbě nového šumu je třeba stisknout tlačítko uzamknout</p>
    <p class="last"><i>Pozn.: pro odstranění "živého" šumu stačí určit počet bodů na hodnotu 0</i></p>
</div>
{% endblock %}

web/MGWeb/templates/home.html
{% extends 'base.html' %}





{% block content %}
<div class="container-lxg mt-5 ml-5">
        <h3>MarkoGebra</h3>
        <p>Apliakce pro jednoduchou tvorbu grafů, jejich úpravu a následné uložení ve formátu png.</p>
        </div>
      <div class="container-lxg mt-5 ml-5">
          <h3>Funkce aplikace</h3>
          <p>MarkoGebra má celkem 4 způsopby grafování.</p>
          <h5>Matematické</h5>
          <p>Body a funkce.</p>
          <h5>Koláčový graf</h5>
          <p>Základní vizualizace statistiky.</p>
          <h5>Sloupcový graf</h5>
          <p>Základní vizualizace statistiky.</p>
          <h5>Náhodný šum</h5>
          <p>Vizualizace náhodného šumu.</p>
      </div>
{% endblock %}